<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>RemoteTech</Description>
    <Version>1.9.0</Version>

    <TargetFramework>net4.8</TargetFramework>
    <LangVersion>13</LangVersion>

    <BinariesOutputRelativePath>GameData\RemoteTech</BinariesOutputRelativePath>
    <KSPBT_GenerateKSPAssemblyAttribute>true</KSPBT_GenerateKSPAssemblyAttribute>
    <KSPBT_GenerateKSPAssemblyDependencyAttributes>true</KSPBT_GenerateKSPAssemblyDependencyAttributes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="0.0.4" />

    <Reference Include="$(KSPRoot)/GameData/000_KSPBurst/Plugins/Unity.*.dll">
      <Private>false</Private>
      <KSPAssemblyName>KSPBurst</KSPAssemblyName>
    </Reference>
  </ItemGroup>
</Project>